package agent

import (
	"fmt"
	"log/slog"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
)

// ContainerRuntime represents the detected container runtime
type ContainerRuntime struct {
	Type    string // "docker" or "podman"
	Command string // actual command to use
	logger  *slog.Logger
}

// DetectContainerRuntime detects whether Docker or Podman is installed
// and sets up the appropriate command to use
func DetectContainerRuntime(logger *slog.Logger) (*ContainerRuntime, error) {
	// Check for Docker first
	if _, err := exec.LookPath("docker"); err == nil {
		// Docker is installed, verify it's working
		cmd := exec.Command("docker", "version")
		if err := cmd.Run(); err == nil {
			logger.Info("Detected container runtime", "type", "docker")
			return &ContainerRuntime{
				Type:    "docker",
				Command: "docker",
				logger:  logger,
			}, nil
		}
		logger.Warn("Docker command found but not working", "error", err)
	}

	// Check for Podman
	if _, err := exec.LookPath("podman"); err == nil {
		// Podman is installed, verify it's working
		cmd := exec.Command("podman", "version")
		if err := cmd.Run(); err == nil {
			logger.Info("Detected container runtime", "type", "podman")

			// Verify podman-compose is installed (required to avoid docker-compose delegation)
			if _, err := exec.LookPath("podman-compose"); err != nil {
				logger.Error("podman-compose not found - required for Podman runtime")
				return nil, fmt.Errorf("podman-compose is required when using Podman. Install it with: pip install podman-compose")
			}

			// Configure Podman to use podman-compose instead of delegating to docker-compose
			if err := setupPodmanComposeProvider(logger); err != nil {
				logger.Warn("Failed to configure Podman compose provider", "error", err)
			}

			// Setup Podman socket for Docker compatibility
			if err := setupPodmanSocket(logger); err != nil {
				logger.Warn("Failed to setup Podman socket", "error", err)
			}

			// Create docker alias/wrapper script if it doesn't exist
			if err := setupDockerAlias(logger); err != nil {
				logger.Warn("Failed to setup docker alias, using podman directly", "error", err)
			}

			return &ContainerRuntime{
				Type:    "podman",
				Command: "podman",
				logger:  logger,
			}, nil
		}
		logger.Warn("Podman command found but not working", "error", err)
	}

	return nil, fmt.Errorf("no container runtime found - please install Docker or Podman")
}

// setupDockerAlias creates a docker alias for podman compatibility
func setupDockerAlias(logger *slog.Logger) error {
	// Check if docker command already exists
	if _, err := exec.LookPath("docker"); err == nil {
		logger.Debug("Docker command already exists, skipping alias creation")
		return nil
	}

	// Create a wrapper script in a user-local bin directory
	homeDir, err := os.UserHomeDir()
	if err != nil {
		return fmt.Errorf("failed to get home directory: %w", err)
	}

	localBin := filepath.Join(homeDir, ".local", "bin")

	// Create the directory if it doesn't exist
	if err := os.MkdirAll(localBin, 0755); err != nil {
		return fmt.Errorf("failed to create local bin directory: %w", err)
	}

	dockerScript := filepath.Join(localBin, "docker")

	// Create the wrapper script
	scriptContent := `#!/bin/sh
# Docker compatibility wrapper for Podman
# Auto-generated by Lixy agent
exec podman "$@"
`

	if err := os.WriteFile(dockerScript, []byte(scriptContent), 0755); err != nil {
		return fmt.Errorf("failed to create docker wrapper script: %w", err)
	}

	logger.Info("Created docker alias for podman",
		"script", dockerScript,
		"note", "Add ~/.local/bin to PATH if not already present")

	// Check if PATH includes ~/.local/bin
	pathEnv := os.Getenv("PATH")
	if !containsSubstr(pathEnv, localBin) {
		logger.Warn("~/.local/bin is not in PATH",
			"suggestion", "Add 'export PATH=$HOME/.local/bin:$PATH' to your shell profile")
	}

	return nil
}

// setupPodmanComposeProvider configures Podman to use podman-compose instead of docker-compose
func setupPodmanComposeProvider(logger *slog.Logger) error {
	homeDir, err := os.UserHomeDir()
	if err != nil {
		return fmt.Errorf("failed to get home directory: %w", err)
	}

	// Create containers config directory
	configDir := filepath.Join(homeDir, ".config", "containers")
	if err := os.MkdirAll(configDir, 0755); err != nil {
		return fmt.Errorf("failed to create containers config directory: %w", err)
	}

	configPath := filepath.Join(configDir, "containers.conf")

	// Check if config already exists and has compose_providers set
	if data, err := os.ReadFile(configPath); err == nil {
		content := string(data)
		if strings.Contains(content, "compose_providers") {
			logger.Debug("Podman compose provider already configured")
			return nil
		}
	}

	// Read existing config or create new one
	existingConfig := ""
	if data, err := os.ReadFile(configPath); err == nil {
		existingConfig = string(data)
	}

	// Add compose_providers configuration
	composeConfig := `
# Lixy: Configure Podman to use podman-compose instead of docker-compose
# This prevents delegation to docker-compose which causes authentication issues
[engine]
compose_providers=["podman-compose"]
`

	// Append to existing config or create new
	newConfig := existingConfig
	if !strings.Contains(existingConfig, "[engine]") {
		newConfig += composeConfig
	} else {
		// Insert compose_providers into existing [engine] section
		lines := strings.Split(existingConfig, "\n")
		var result []string
		inEngineSection := false
		added := false

		for _, line := range lines {
			result = append(result, line)
			if strings.TrimSpace(line) == "[engine]" {
				inEngineSection = true
			} else if inEngineSection && strings.HasPrefix(strings.TrimSpace(line), "[") {
				inEngineSection = false
			}

			if inEngineSection && !added && !strings.Contains(line, "compose_providers") {
				result = append(result, `compose_providers=["podman-compose"]`)
				added = true
			}
		}
		newConfig = strings.Join(result, "\n")
	}

	if err := os.WriteFile(configPath, []byte(newConfig), 0644); err != nil {
		return fmt.Errorf("failed to write containers.conf: %w", err)
	}

	logger.Info("Configured Podman to use podman-compose",
		"config", configPath,
		"note", "Podman will now use podman-compose instead of delegating to docker-compose")

	return nil
}

// setupPodmanSocket ensures Podman socket is running and sets DOCKER_HOST
func setupPodmanSocket(logger *slog.Logger) error {
	// Start Podman socket service if not running
	// On macOS, use podman machine
	if runtime.GOOS == "darwin" {
		// Check if podman machine is running
		cmd := exec.Command("podman", "machine", "inspect", "--format", "{{.State}}")
		output, err := cmd.Output()
		if err != nil {
			logger.Warn("Failed to check podman machine status", "error", err)
			return fmt.Errorf("podman machine not accessible: %w", err)
		}

		state := strings.TrimSpace(string(output))
		if state != "running" {
			logger.Info("Podman machine not running, attempting to start...")
			startCmd := exec.Command("podman", "machine", "start")
			if err := startCmd.Run(); err != nil {
				return fmt.Errorf("failed to start podman machine: %w", err)
			}
			logger.Info("Podman machine started successfully")
		}

		// Get the podman socket path
		socketCmd := exec.Command("podman", "machine", "inspect", "--format", "{{.ConnectionInfo.PodmanSocket.Path}}")
		socketOutput, err := socketCmd.Output()
		if err != nil {
			logger.Warn("Failed to get podman socket path", "error", err)
		} else {
			socketPath := strings.TrimSpace(string(socketOutput))
			if socketPath != "" {
				// Set DOCKER_HOST environment variable
				dockerHost := fmt.Sprintf("unix://%s", socketPath)
				os.Setenv("DOCKER_HOST", dockerHost)
				logger.Info("Set DOCKER_HOST for Podman compatibility", "docker_host", dockerHost)
			}
		}
	} else {
		// On Linux, enable and start podman socket
		// Try to start podman socket using systemd (user service)
		cmd := exec.Command("systemctl", "--user", "start", "podman.socket")
		if err := cmd.Run(); err != nil {
			logger.Debug("Failed to start podman socket via systemd", "error", err)
			// Fall back to getting the socket path directly
		}

		// Get the podman socket path
		// Try XDG_RUNTIME_DIR first
		runtimeDir := os.Getenv("XDG_RUNTIME_DIR")
		if runtimeDir != "" {
			socketPath := filepath.Join(runtimeDir, "podman", "podman.sock")
			if _, err := os.Stat(socketPath); err == nil {
				dockerHost := fmt.Sprintf("unix://%s", socketPath)
				os.Setenv("DOCKER_HOST", dockerHost)
				logger.Info("Set DOCKER_HOST for Podman compatibility", "docker_host", dockerHost)
			}
		}
	}

	return nil
}

// VerifyDockerCompose checks if docker-compose or podman-compose is available
func VerifyDockerCompose(rt *ContainerRuntime, logger *slog.Logger) error {
	// Try docker compose (new plugin syntax)
	if rt.Type == "docker" {
		cmd := exec.Command("docker", "compose", "version")
		if err := cmd.Run(); err == nil {
			logger.Info("Docker Compose plugin detected")
			return nil
		}
	}

	// Try podman compose (new plugin syntax)
	if rt.Type == "podman" {
		cmd := exec.Command("podman", "compose", "version")
		if err := cmd.Run(); err == nil {
			logger.Info("Podman Compose plugin detected")
			return nil
		}

		// Fallback to standalone podman-compose
		if _, err := exec.LookPath("podman-compose"); err == nil {
			cmd := exec.Command("podman-compose", "--version")
			if err := cmd.Run(); err == nil {
				logger.Info("Podman Compose (standalone) detected")
				return nil
			}
		}

		// Also check for docker-compose with podman
		cmd = exec.Command("docker-compose", "--version")
		if err := cmd.Run(); err == nil {
			logger.Info("Docker Compose detected (will use with Podman)")
			return nil
		}
	}

	// Try standalone docker-compose
	if _, err := exec.LookPath("docker-compose"); err == nil {
		cmd := exec.Command("docker-compose", "--version")
		if err := cmd.Run(); err == nil {
			logger.Info("Docker Compose (standalone) detected")
			return nil
		}
	}

	return fmt.Errorf("no compose tool found - please install docker-compose or podman-compose")
}

// GetComposeCommand returns the appropriate compose command to use
func (cr *ContainerRuntime) GetComposeCommand() []string {
	// Try plugin syntax first (docker compose / podman compose)
	cmd := exec.Command(cr.Command, "compose", "version")
	if err := cmd.Run(); err == nil {
		cr.logger.Debug("Using compose plugin", "command", cr.Command+" compose")
		return []string{cr.Command, "compose"}
	}

	// Try standalone docker-compose
	if _, err := exec.LookPath("docker-compose"); err == nil {
		cmd := exec.Command("docker-compose", "--version")
		if err := cmd.Run(); err == nil {
			cr.logger.Debug("Using standalone docker-compose")
			return []string{"docker-compose"}
		}
	}

	// Try standalone podman-compose
	if cr.Type == "podman" {
		if _, err := exec.LookPath("podman-compose"); err == nil {
			cmd := exec.Command("podman-compose", "--version")
			if err := cmd.Run(); err == nil {
				cr.logger.Debug("Using standalone podman-compose")
				return []string{"podman-compose"}
			}
		}
	}

	// Default to plugin syntax and let it fail with a clear error
	cr.logger.Warn("No compose command detected, defaulting to plugin syntax")
	return []string{cr.Command, "compose"}
}

// containsSubstr checks if a string contains a substring
func containsSubstr(s, substr string) bool {
	return len(s) >= len(substr) && (s == substr ||
		(len(s) > len(substr) && (s[:len(substr)] == substr || s[len(s)-len(substr):] == substr)) ||
		len(s) > len(substr)+1 && s[1:len(substr)+1] == substr)
}

// AuthenticateRegistry logs into a container registry with the provided credentials
// dockerConfigDir is optional - if provided, credentials will be stored there
func (cr *ContainerRuntime) AuthenticateRegistry(registry, username, token string) error {
	return cr.AuthenticateRegistryWithConfig(registry, username, token, "")
}

// AuthenticateRegistryWithConfig logs into a container registry with custom config directory
func (cr *ContainerRuntime) AuthenticateRegistryWithConfig(registry, username, token, dockerConfigDir string) error {
	cr.logger.Info("Authenticating with registry",
		"registry", registry,
		"username", username,
		"config_dir", dockerConfigDir)

	// Use docker/podman login command
	cmd := exec.Command(cr.Command, "login", registry,
		"--username", username,
		"--password-stdin")

	// Set DOCKER_CONFIG if provided
	if dockerConfigDir != "" {
		cmd.Env = append(os.Environ(), fmt.Sprintf("DOCKER_CONFIG=%s", dockerConfigDir))
	}

	// Pass token via stdin for security
	cmd.Stdin = strings.NewReader(token)

	output, err := cmd.CombinedOutput()
	if err != nil {
		cr.logger.Error("Failed to authenticate with registry",
			"registry", registry,
			"error", err,
			"output", string(output))
		return fmt.Errorf("registry authentication failed: %w", err)
	}

	cr.logger.Info("Successfully authenticated with registry",
		"registry", registry,
		"config_dir", dockerConfigDir)
	return nil
}

// LogoutRegistry logs out from a container registry
func (cr *ContainerRuntime) LogoutRegistry(registry string) error {
	cr.logger.Info("Logging out from registry", "registry", registry)

	cmd := exec.Command(cr.Command, "logout", registry)
	output, err := cmd.CombinedOutput()
	if err != nil {
		cr.logger.Warn("Failed to logout from registry",
			"registry", registry,
			"error", err,
			"output", string(output))
		return fmt.Errorf("registry logout failed: %w", err)
	}

	cr.logger.Info("Successfully logged out from registry", "registry", registry)
	return nil
}

// PullImageWithAuth pulls an image after authenticating with the registry
func (cr *ContainerRuntime) PullImageWithAuth(image, registry, username, token string) error {
	// Authenticate first
	if err := cr.AuthenticateRegistry(registry, username, token); err != nil {
		return fmt.Errorf("authentication failed: %w", err)
	}

	// Ensure we logout after pulling (defer)
	defer func() {
		if err := cr.LogoutRegistry(registry); err != nil {
			cr.logger.Warn("Failed to logout after pull", "error", err)
		}
	}()

	// Pull the image
	cr.logger.Info("Pulling image", "image", image)
	cmd := exec.Command(cr.Command, "pull", image)
	output, err := cmd.CombinedOutput()
	if err != nil {
		cr.logger.Error("Failed to pull image",
			"image", image,
			"error", err,
			"output", string(output))
		return fmt.Errorf("image pull failed: %w", err)
	}

	cr.logger.Info("Successfully pulled image", "image", image)
	return nil
}

// PullImage pulls an image without authentication (for public images)
func (cr *ContainerRuntime) PullImage(image string) error {
	cr.logger.Info("Pulling image", "image", image)

	cmd := exec.Command(cr.Command, "pull", image)
	output, err := cmd.CombinedOutput()
	if err != nil {
		cr.logger.Error("Failed to pull image",
			"image", image,
			"error", err,
			"output", string(output))
		return fmt.Errorf("image pull failed: %w", err)
	}

	cr.logger.Info("Successfully pulled image", "image", image)
	return nil
}

// IsPrivateRegistry determines if an image is from a private registry.
// An image is considered private when its first path component looks like a
// hostname (contains a '.' or ':', or equals "localhost"). Docker Hub images
// such as "nginx" or "myorg/myimage" do not match and are treated as public.
func IsPrivateRegistry(image string) (bool, string) {
	// Strip tag/digest to get the bare image reference
	ref := strings.SplitN(image, ":", 2)[0]
	ref = strings.SplitN(ref, "@", 2)[0]

	// The first slash-delimited component is the potential hostname
	first := strings.SplitN(ref, "/", 2)[0]

	// A component is a hostname if it contains a dot, a colon (port), or is "localhost"
	if strings.ContainsAny(first, ".:") || first == "localhost" {
		return true, first
	}

	return false, ""
}
