package client

import (
	"fmt"
	"log/slog"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
)

// ContainerRuntime represents the detected container runtime
type ContainerRuntime struct {
	Type    string // "docker" or "podman"
	Command string // actual command to use
	logger  *slog.Logger
}

// DetectContainerRuntime detects whether Docker or Podman is installed
// and sets up the appropriate command to use
func DetectContainerRuntime(logger *slog.Logger) (*ContainerRuntime, error) {
	// Check for Docker first
	if _, err := exec.LookPath("docker"); err == nil {
		// Docker is installed, verify it's working
		cmd := exec.Command("docker", "version")
		if err := cmd.Run(); err == nil {
			logger.Info("Detected container runtime", "type", "docker")
			return &ContainerRuntime{
				Type:    "docker",
				Command: "docker",
				logger:  logger,
			}, nil
		}
		logger.Warn("Docker command found but not working", "error", err)
	}

	// Check for Podman
	if _, err := exec.LookPath("podman"); err == nil {
		// Podman is installed, verify it's working
		cmd := exec.Command("podman", "version")
		if err := cmd.Run(); err == nil {
			logger.Info("Detected container runtime", "type", "podman")

			// Setup Podman socket for Docker compatibility
			if err := setupPodmanSocket(logger); err != nil {
				logger.Warn("Failed to setup Podman socket", "error", err)
			}

			// Create docker alias/wrapper script if it doesn't exist
			if err := setupDockerAlias(logger); err != nil {
				logger.Warn("Failed to setup docker alias, using podman directly", "error", err)
			}

			return &ContainerRuntime{
				Type:    "podman",
				Command: "podman",
				logger:  logger,
			}, nil
		}
		logger.Warn("Podman command found but not working", "error", err)
	}

	return nil, fmt.Errorf("no container runtime found - please install Docker or Podman")
}

// setupDockerAlias creates a docker alias for podman compatibility
func setupDockerAlias(logger *slog.Logger) error {
	// Check if docker command already exists
	if _, err := exec.LookPath("docker"); err == nil {
		logger.Debug("Docker command already exists, skipping alias creation")
		return nil
	}

	// Create a wrapper script in a user-local bin directory
	homeDir, err := os.UserHomeDir()
	if err != nil {
		return fmt.Errorf("failed to get home directory: %w", err)
	}

	localBin := filepath.Join(homeDir, ".local", "bin")

	// Create the directory if it doesn't exist
	if err := os.MkdirAll(localBin, 0755); err != nil {
		return fmt.Errorf("failed to create local bin directory: %w", err)
	}

	dockerScript := filepath.Join(localBin, "docker")

	// Create the wrapper script
	scriptContent := `#!/bin/sh
# Docker compatibility wrapper for Podman
# Auto-generated by Lixy agent
exec podman "$@"
`

	if err := os.WriteFile(dockerScript, []byte(scriptContent), 0755); err != nil {
		return fmt.Errorf("failed to create docker wrapper script: %w", err)
	}

	logger.Info("Created docker alias for podman",
		"script", dockerScript,
		"note", "Add ~/.local/bin to PATH if not already present")

	// Check if PATH includes ~/.local/bin
	pathEnv := os.Getenv("PATH")
	if !contains(pathEnv, localBin) {
		logger.Warn("~/.local/bin is not in PATH",
			"suggestion", "Add 'export PATH=$HOME/.local/bin:$PATH' to your shell profile")
	}

	return nil
}

// setupPodmanSocket ensures Podman socket is running and sets DOCKER_HOST
func setupPodmanSocket(logger *slog.Logger) error {
	// Start Podman socket service if not running
	// On macOS, use podman machine
	if runtime.GOOS == "darwin" {
		// Check if podman machine is running
		cmd := exec.Command("podman", "machine", "inspect", "--format", "{{.State}}")
		output, err := cmd.Output()
		if err != nil {
			logger.Warn("Failed to check podman machine status", "error", err)
			return fmt.Errorf("podman machine not accessible: %w", err)
		}

		state := strings.TrimSpace(string(output))
		if state != "running" {
			logger.Info("Podman machine not running, attempting to start...")
			startCmd := exec.Command("podman", "machine", "start")
			if err := startCmd.Run(); err != nil {
				return fmt.Errorf("failed to start podman machine: %w", err)
			}
			logger.Info("Podman machine started successfully")
		}

		// Get the podman socket path
		socketCmd := exec.Command("podman", "machine", "inspect", "--format", "{{.ConnectionInfo.PodmanSocket.Path}}")
		socketOutput, err := socketCmd.Output()
		if err != nil {
			logger.Warn("Failed to get podman socket path", "error", err)
		} else {
			socketPath := strings.TrimSpace(string(socketOutput))
			if socketPath != "" {
				// Set DOCKER_HOST environment variable
				dockerHost := fmt.Sprintf("unix://%s", socketPath)
				os.Setenv("DOCKER_HOST", dockerHost)
				logger.Info("Set DOCKER_HOST for Podman compatibility", "docker_host", dockerHost)
			}
		}
	} else {
		// On Linux, enable and start podman socket
		// Try to start podman socket using systemd (user service)
		cmd := exec.Command("systemctl", "--user", "start", "podman.socket")
		if err := cmd.Run(); err != nil {
			logger.Debug("Failed to start podman socket via systemd", "error", err)
			// Fall back to getting the socket path directly
		}

		// Get the podman socket path
		// Try XDG_RUNTIME_DIR first
		runtimeDir := os.Getenv("XDG_RUNTIME_DIR")
		if runtimeDir != "" {
			socketPath := filepath.Join(runtimeDir, "podman", "podman.sock")
			if _, err := os.Stat(socketPath); err == nil {
				dockerHost := fmt.Sprintf("unix://%s", socketPath)
				os.Setenv("DOCKER_HOST", dockerHost)
				logger.Info("Set DOCKER_HOST for Podman compatibility", "docker_host", dockerHost)
			}
		}
	}

	return nil
}

// VerifyDockerCompose checks if docker-compose or podman-compose is available
func VerifyDockerCompose(runtime *ContainerRuntime, logger *slog.Logger) error {
	// Try docker compose (new plugin syntax)
	if runtime.Type == "docker" {
		cmd := exec.Command("docker", "compose", "version")
		if err := cmd.Run(); err == nil {
			logger.Info("Docker Compose plugin detected")
			return nil
		}
	}

	// Try podman compose (new plugin syntax)
	if runtime.Type == "podman" {
		cmd := exec.Command("podman", "compose", "version")
		if err := cmd.Run(); err == nil {
			logger.Info("Podman Compose plugin detected")
			return nil
		}

		// Fallback to standalone podman-compose
		if _, err := exec.LookPath("podman-compose"); err == nil {
			cmd := exec.Command("podman-compose", "--version")
			if err := cmd.Run(); err == nil {
				logger.Info("Podman Compose (standalone) detected")
				return nil
			}
		}

		// Also check for docker-compose with podman
		cmd = exec.Command("docker-compose", "--version")
		if err := cmd.Run(); err == nil {
			logger.Info("Docker Compose detected (will use with Podman)")
			return nil
		}
	}

	// Try standalone docker-compose
	if _, err := exec.LookPath("docker-compose"); err == nil {
		cmd := exec.Command("docker-compose", "--version")
		if err := cmd.Run(); err == nil {
			logger.Info("Docker Compose (standalone) detected")
			return nil
		}
	}

	return fmt.Errorf("no compose tool found - please install docker-compose or podman-compose")
}

// GetComposeCommand returns the appropriate compose command to use
func (cr *ContainerRuntime) GetComposeCommand() []string {
	// Try plugin syntax first (docker compose / podman compose)
	cmd := exec.Command(cr.Command, "compose", "version")
	if err := cmd.Run(); err == nil {
		cr.logger.Debug("Using compose plugin", "command", cr.Command+" compose")
		return []string{cr.Command, "compose"}
	}

	// Try standalone docker-compose
	if _, err := exec.LookPath("docker-compose"); err == nil {
		cmd := exec.Command("docker-compose", "--version")
		if err := cmd.Run(); err == nil {
			cr.logger.Debug("Using standalone docker-compose")
			return []string{"docker-compose"}
		}
	}

	// Try standalone podman-compose
	if cr.Type == "podman" {
		if _, err := exec.LookPath("podman-compose"); err == nil {
			cmd := exec.Command("podman-compose", "--version")
			if err := cmd.Run(); err == nil {
				cr.logger.Debug("Using standalone podman-compose")
				return []string{"podman-compose"}
			}
		}
	}

	// Default to plugin syntax and let it fail with a clear error
	cr.logger.Warn("No compose command detected, defaulting to plugin syntax")
	return []string{cr.Command, "compose"}
}

// contains checks if a string contains a substring
func contains(s, substr string) bool {
	return len(s) >= len(substr) && (s == substr ||
		(len(s) > len(substr) && (s[:len(substr)] == substr || s[len(s)-len(substr):] == substr)) ||
		len(s) > len(substr)+1 && s[1:len(substr)+1] == substr)
}

// AuthenticateRegistry logs into a container registry with the provided credentials
func (cr *ContainerRuntime) AuthenticateRegistry(registry, username, token string) error {
	cr.logger.Info("Authenticating with registry",
		"registry", registry,
		"username", username)

	// Use docker/podman login command
	cmd := exec.Command(cr.Command, "login", registry,
		"--username", username,
		"--password-stdin")

	// Pass token via stdin for security
	cmd.Stdin = strings.NewReader(token)

	output, err := cmd.CombinedOutput()
	if err != nil {
		cr.logger.Error("Failed to authenticate with registry",
			"registry", registry,
			"error", err,
			"output", string(output))
		return fmt.Errorf("registry authentication failed: %w", err)
	}

	cr.logger.Info("Successfully authenticated with registry",
		"registry", registry)
	return nil
}

// LogoutRegistry logs out from a container registry
func (cr *ContainerRuntime) LogoutRegistry(registry string) error {
	cr.logger.Info("Logging out from registry", "registry", registry)

	cmd := exec.Command(cr.Command, "logout", registry)
	output, err := cmd.CombinedOutput()
	if err != nil {
		cr.logger.Warn("Failed to logout from registry",
			"registry", registry,
			"error", err,
			"output", string(output))
		return fmt.Errorf("registry logout failed: %w", err)
	}

	cr.logger.Info("Successfully logged out from registry", "registry", registry)
	return nil
}

// PullImageWithAuth pulls an image after authenticating with the registry
func (cr *ContainerRuntime) PullImageWithAuth(image, registry, username, token string) error {
	// Authenticate first
	if err := cr.AuthenticateRegistry(registry, username, token); err != nil {
		return fmt.Errorf("authentication failed: %w", err)
	}

	// Ensure we logout after pulling (defer)
	defer func() {
		if err := cr.LogoutRegistry(registry); err != nil {
			cr.logger.Warn("Failed to logout after pull", "error", err)
		}
	}()

	// Pull the image
	cr.logger.Info("Pulling image", "image", image)
	cmd := exec.Command(cr.Command, "pull", image)
	output, err := cmd.CombinedOutput()
	if err != nil {
		cr.logger.Error("Failed to pull image",
			"image", image,
			"error", err,
			"output", string(output))
		return fmt.Errorf("image pull failed: %w", err)
	}

	cr.logger.Info("Successfully pulled image", "image", image)
	return nil
}

// PullImage pulls an image without authentication (for public images)
func (cr *ContainerRuntime) PullImage(image string) error {
	cr.logger.Info("Pulling image", "image", image)

	cmd := exec.Command(cr.Command, "pull", image)
	output, err := cmd.CombinedOutput()
	if err != nil {
		cr.logger.Error("Failed to pull image",
			"image", image,
			"error", err,
			"output", string(output))
		return fmt.Errorf("image pull failed: %w", err)
	}

	cr.logger.Info("Successfully pulled image", "image", image)
	return nil
}

// IsPrivateRegistry determines if an image is from a private registry
func IsPrivateRegistry(image string) (bool, string) {
	// Check if image starts with a known private registry
	if strings.HasPrefix(image, "ghcr.io/") {
		return true, "ghcr.io"
	}

	// Add more private registries as needed
	// if strings.HasPrefix(image, "gcr.io/") {
	// 	return true, "gcr.io"
	// }

	// Docker Hub images without registry prefix are public by default
	// unless they're in a private organization
	return false, ""
}
